Enhance triton functionality to allow use of custom cuda toolkit at runtime (#4237)
Fixes https://github.com/triton-lang/triton/issues/4224

As introduced in https://github.com/triton-lang/triton/issues/4224, this
PR addresses two main issues in source build Triton with custom cuda
toolkit:

1. `cupti_include_dir` lookup path for CMake should also include
`TRITON_CUPTI_PATH`, as the `TRITON_XXX_PATH` seems to the standard for
a custom triton build environment variables.
2. As described in the linked issue, when we specify a
`TRITON_CUDART_PATH`, those cuda RT headers from conda will not be
downloaded to triton/third_party paths. This makes the default include
path bundled in Triton python package empty and thus leads to `fatal
error: cuda.h: No such file or directory` error.
If we're supporting users to "bring your own cuda toolkit" to build
triton from source, we should also support them to run triton compile
with their own cuda toolkit runtime.

The core Triton is a small number of people, and we receive many PRs
(thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the
following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them.

- [X] I am not making a trivial change, such as fixing a typo in a
comment.

- [X] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [ ] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
- [X] This PR does not need a test because `This PR enhances custom
build options and won't affect the default build. Default build will be
validated by existing CI`.

- Select one of the following.
  - [X] I have not added any `lit` tests.
- [ ] The `lit` tests I have added follow these [best
practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
including the "tests should be minimal" section. (Usually running Python
code
    and using the instructions it generates is not minimal.)