Preserve information needed for repro when ptxas segfaults (#4301)
## Summary:

Currently when `ptxas` segfaults, Triton prints a message asking the
user to confirm the crash by running `ptxas the_bad_input.ptx`. However:
* the exact repro command is not shown to the user
* the bad `.ptx` file is not preserved

This PR preserves the bad `.ptx` file and prints the exact repro
command. This makes it possible to actually repro the segfault and
report the bug upstream.

## Before:
```
$ python test.py
...
RuntimeError: Please run `ptxas /tmp/tmpzt0bfsko.ptx` to confirm that this is a bug in `ptxas`
```
Necessary files are not preserved:
```
$ ptxas /tmp/tmpzt0bfsko.ptx
ptxas fatal   : Input file '/tmp/tmpzt0bfsko.ptx' could not be opened
ptxas fatal   : Ptx assembly aborted due to errors
```

## After:
```
$ python test.py
...
RuntimeError: `ptxas` raised SIGSEGV
`ptxas` stderr:

Repro command: /data/users/embg/triton/python/triton/backends/nvidia/bin/ptxas -lineinfo -v --gpu-name=sm_90a /tmp/tmpzt0bfsko.ptx -o /tmp/tmpzt0bfsko.ptx.o 2> /tmp/tmpukzluqfn.log
```
Necessary files are preserved:
```
$ ls -l /tmp/tmpzt0bfsko.ptx
-rw------- 1 embg users 8054 Jul 29 09:55 /tmp/tmpzt0bfsko.ptx
```
Now we can repro the segfault and report upstream to nvidia:
```
$ /data/users/embg/triton/python/triton/backends/nvidia/bin/ptxas -lineinfo -v --gpu-name=sm_90a /tmp/tmpzt0bfsko.ptx -o /tmp/tmpzt0bfsko.ptx.o 2> /tmp/tmpukzluqfn.log
Segmentation fault (core dumped)
```

## Checklist:

- [x] I am not making a trivial change, such as fixing a typo in a
comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
- [x] This PR does not need a test because: "hopefully nvidia fixes the
ptx segfault, which would break our test!"

- Select one of the following.
  - [x] I have not added any `lit` tests.